set_languages("c++20")
add_requires("libsdl", "libsdl_image", "libsdl_mixer", "libsdl_ttf", "box2d")
add_rules("mode.release", "mode.debug")
includes("core", "modules")
target("hex")
    set_kind("binary")
    add_deps("hexcore", "modules")
    add_packages("libsdl", "libsdl_image", "libsdl_mixer", "libsdl_ttf", "box2d")
    add_files("*.cpp")
